### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by joncorrin** [MattewEon/ngx-heyl-social-login#1]
Is there a way to logout with this library?

I dont see anything for it.

**Comment by MattewEon** [comment]
Maybe I'm wrong, but I don't think that you are really logged in. Facebook/Google send you some data, then you will have to handle if the user is logged in on not in your application

**Comment by joncorrin** [comment]
Ok, fair enough. Im just used to having the logout option on libraries but I see you run a logout function. Now Im having a real issue though. 

```
Not a valid origin for the client: http://localhost:4200 has not been whitelisted for client ID XXXXXX.apps.googleusercontent.com.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID.
```

But here is my developers console 
![screen shot 2017-09-26 at 8 11 04 am](https://user-images.githubusercontent.com/23392999/30867996-4bea8cd8-a292-11e7-848b-f7faafd32a5d.png)

Im pretty sure that means its whitelisted.

**Comment by MattewEon** [comment]
Did you just added the localhost:4200 line few times ago ? I think some times it takes several minutes / hour to update. 

In the meantime you can check the Facebook login part. 

And don't hesitate to upgrade this module if you want so :)

**Comment by joncorrin** [comment]
Ok, Ill wait. And Facebook is working great. I was using another angular library that was really buggy with facebook. So thanks for creating this which takes google and facebook!
